### ISSUE TITLE
Using a home assistant temp sensor for the remote temp

### ISSUE THREAD

**Issue by fresnoboy** [akamali/mhk1_mqtt#5]
How do I send the value of a home assistant temp sensor  so it can be used as a remote room temp?

**Comment by akamali** [comment]
Please refer to instructions in the README for example of how to get it working with HA: https://github.com/akamali/mhk1_mqtt#integration-with-home-assistant, `temperature_command_topic` should be relevant.

For more generic Home Assistant questions it's best to refer to HA documentation.
